# Site settings
title: Wang Yan
name: Wu Wangyan # your name
email: zxacd@qq.com # your email address
description: >
   让孩子活在梦里 # this means to ignore newlines until "baseurl:"
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://www.xinyiheyi.net" # the base hostname & protocol for your site
twitter_username:  # your Twitter username
github_username: 4ga1n # your Github username
disqus_username: itisbenjamin # your disqus username

google-analytics:  # add it if you have one

skillstree: true # turn on or off the skills tree in about page

# Build settings
permalink: none
markdown: kramdown
